[dbt] br_ce_fortaleza_sefin_dados_imobiliarios
basedosdados/queries-basedosdados pull request #168
Opened 2023-08-17 14:46 UTC by tricktx

2023-08-17 18:45 UTC, laura-l-amaral requested changes

2023-08-17 18:45 UTC, laura-l-amaral commented on models/br_ce_fortaleza_sefin_dados_imobiliarios/face_quadra.sql
> +SAFE_CAST(geometria AS STRING) geometria,
a geometria tem que ficar como tipo geometria, que nem na tabela br_geobr_mapas.biomas ou na tabela de CEP

2023-08-17 18:45 UTC, laura-l-amaral commented on models/br_ce_fortaleza_sefin_dados_imobiliarios/face_quadra.sql
> +SAFE_CAST(latitude AS float64) latitude,
latitude e longitude são valores que devem ficar em -90:90 e 0:180. Tem que ver o que aconteceu ai

2023-08-17 18:45 UTC, laura-l-amaral commented on models/br_ce_fortaleza_sefin_dados_imobiliarios/face_quadra.sql
> +FROM basedosdados-staging.br_ce_fortaleza_sefin_dados_imobiliarios_staging.face_quadra AS t
acho que o nome do conjunto tinha que padronizar com o de sp e deixar como iptu

2023-08-17 18:45 UTC, laura-l-amaral commented on models/br_ce_fortaleza_sefin_dados_imobiliarios/face_quadra.sql
> +SAFE_CAST(agua AS BOOL) agua,
nao ta igual a arquitetura

2023-08-17 18:45 UTC, laura-l-amaral commented on models/br_ce_fortaleza_sefin_dados_imobiliarios/face_quadra.sql
> +SAFE_CAST(sarjeta AS BOOL) sarjeta,
sabe pq tem tanto calor nulo nessas variaveis booleanas?

2023-08-17 18:49 UTC, tricktx commented on models/br_ce_fortaleza_sefin_dados_imobiliarios/face_quadra.sql
> +SAFE_CAST(geometria AS STRING) geometria,
Me espelhei em algumas tabelas do GEOBR e estão como strings, irei ajuda-la nesse instante.

2023-08-17 18:54 UTC, tricktx commented on models/br_ce_fortaleza_sefin_dados_imobiliarios/face_quadra.sql
> +SAFE_CAST(agua AS BOOL) agua,
Referente ao BOOL? A nomeação da variável no Google Cloud é por padrão BOOL e no Django é Boolean. Só deixei igual ao GCP, segue os links:
GCP: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types
Django: https://api.basedosdados.org/admin/v1/table/ccd110fd-80b7-4113-b223-48dd4ddce8e0/change/?_changelist_filters=q%3Dface

2023-08-17 18:58 UTC, tricktx commented on models/br_ce_fortaleza_sefin_dados_imobiliarios/face_quadra.sql
> +FROM basedosdados-staging.br_ce_fortaleza_sefin_dados_imobiliarios_staging.face_quadra AS t
É porque necessariamente estamos falando de uma "modelo" diferente do iptu tradicional. Acredito que quando conseguirmos os dados históricos de 2002-2023, podemos colocar o nome da tabela de iptu, sem problemas. Mas nesse caso específico, não acho válido.

2023-08-17 19:12 UTC, gustavoalcantara commented on models/br_ce_fortaleza_sefin_dados_imobiliarios/face_quadra.sql
> +SAFE_CAST(latitude AS float64) latitude,
Laura, nos dados originais, a lat/long tão em SRC (sistema de coordenadas projetadas). O @tricktx menciona que o datum é UTM 24S. Portanto, pelo padrão que nós temos aqui na BD, aconselho a reprojetar esses valores para o Sistema de Coordenadas Geográficas. Posso ajudar nesse processo, qualquer coisa.

2023-08-17 19:13 UTC, gustavoalcantara commented on models/br_ce_fortaleza_sefin_dados_imobiliarios/face_quadra.sql
> +SAFE_CAST(geometria AS STRING) geometria,
olhe para a tabela de CEP que a Gabi subiu. Tá melhor.

2023-08-17 19:27 UTC, tricktx commented on models/br_ce_fortaleza_sefin_dados_imobiliarios/face_quadra.sql
> +SAFE_CAST(sarjeta AS BOOL) sarjeta,
Os dados nulos já vem da base original, Laura. Realmente não há explicação do motivo.

2023-08-18 02:30 UTC, tricktx commented on models/br_ce_fortaleza_sefin_dados_imobiliarios/face_quadra.sql
> +SAFE_CAST(geometria AS STRING) geometria,
@laura-l-amaral pelo motivo citado acima, uma vez que os dados não estão entre -90:90 e 0:18, o bigquery não aceita o modo GEOGRAPHY.

2023-08-21 12:27 UTC, laura-l-amaral commented on models/br_ce_fortaleza_sefin_dados_imobiliarios/face_quadra.sql
> +SAFE_CAST(agua AS BOOL) agua,
o nome das variaveis ta diferente

2023-08-23 19:21 UTC, closed without merging