[dbt] br_ibge_criacao_municipios
basedosdados/queries-basedosdados pull request #205
Opened 2023-08-30 21:49 UTC by Italo-Engers

Subindo base de criação dos municípios

2023-08-30 22:03 UTC, gabrielle-carv commented on models/br_ibge_criacao_municipios/dados.sql
> +FROM `basedosdados-staging.br_ibge_criacao_municipios_staging.dados` AS t1
se os dados ainda precisarem ir pra staging add em labels o `table-approve`

2023-09-11 13:10 UTC, laura-l-amaral commented on models/br_ibge_criacao_municipios/schema.yml
> +    description: Dados sobre Criação de municípios brasileiros bem como os munícipios originários
remover maiuscula de 'Criação'

2023-09-11 13:11 UTC, laura-l-amaral requested changes

2024-02-27 18:13 UTC, laura-l-amaral commented
replaced by #462

2024-02-27 18:13 UTC, closed without merging