[dbt] br_stf_corte_aberta
basedosdados/queries-basedosdados pull request #281
Opened 2023-09-27 11:39 UTC by tricktx

2023-09-28 17:08 UTC, laura-l-amaral requested changes
Essa tabela não é pra ser 100% bdpro já que tem atualização diária, tem que arrumar o permissionamento

2023-09-29 11:54 UTC, tricktx commented
@laura-l-amaral subi a alteração, pode verificar novamente, por gentileza?

2023-09-29 12:34 UTC, laura-l-amaral commented
@tricktx precisa arrumar os metadados antes de mergear, mas vou dar o approve

2023-09-29 12:35 UTC, laura-l-amaral approved these changes

2023-09-29 19:48 UTC, merged