dbt: br_cgu_servidores_executivo_federal
basedosdados/queries-basedosdados pull request #288
Opened 2023-10-03 19:11 UTC by aspeddro

2023-10-03 22:25 UTC, laura-l-amaral requested changes
Ajustes para serem feitos:

- [ ] incluir alias para todas as tabelas
- [ ] alterar nome das tabelas de cadastro
- [ ] verificar tabelas com datas faltantes

2023-10-03 22:25 UTC, laura-l-amaral commented on models/br_cgu_servidores_executivo_federal/afastamentos.sql
> +        schema = 'br_cgu_servidores_executivo_federal',
incluir alias, definimos que devemos ter `alias=True` em todos os flows

2023-10-03 22:25 UTC, laura-l-amaral commented on models/br_cgu_servidores_executivo_federal/aposentados_cadastro.sql
> +        schema = 'br_cgu_servidores_executivo_federal',
os dados vao ficar mais organizados no BQ se a gente mudar o nome da tabela para cadastro_aposentados, cadastro_pensionistas, cadastro_servidores e cadastro_reserva_refroma_militares. fala comigo pra eu te mostrar com  ajustar isso de maneira rápida

2023-10-03 22:25 UTC, laura-l-amaral commented on models/br_cgu_servidores_executivo_federal/aposentados_cadastro.sql
> +    safe_cast(data_aposentadoria as date) data_aposentadoria,
coluna ta inteira nula no BQ

2023-10-03 22:25 UTC, laura-l-amaral commented on models/br_cgu_servidores_executivo_federal/aposentados_cadastro.sql
> +    ) as data_nomeacao_cargo_funcao,
apenas dados nulos no BQ

2023-10-03 22:25 UTC, laura-l-amaral commented on models/br_cgu_servidores_executivo_federal/observacoes.sql
> +    config(
o que é essa tabela de observações? não entendi o que ela é, ela complementa a tabela de remuneração?

2023-10-04 18:28 UTC, aspeddro commented on models/br_cgu_servidores_executivo_federal/br_cgu_servidores_executivo_federal__cadastro_aposentados.sql
> +    ) as data_aposentadoria,
Verifiquei os dados brutos em staging e é tudo null

2023-10-04 18:28 UTC, aspeddro commented on models/br_cgu_servidores_executivo_federal/afastamentos.sql
> +        schema = 'br_cgu_servidores_executivo_federal',
Feito

2023-10-04 18:29 UTC, aspeddro commented on models/br_cgu_servidores_executivo_federal/aposentados_cadastro.sql
> +    safe_cast(data_aposentadoria as date) data_aposentadoria,
Corrigido

2023-10-24 20:34 UTC, aspeddro commented
Aumentei o mês para 7

2023-10-24 20:57 UTC, laura-l-amaral approved these changes

2023-10-24 20:59 UTC, aspeddro commented on models/br_cgu_servidores_executivo_federal/observacoes.sql
> +    config(
Adicionei uma descrição melhor

2023-10-24 21:05 UTC, merged