[dados] br_firjan_ifgf
basedosdados/queries-basedosdados pull request #358
Opened 2023-12-01 09:19 UTC by lucasnascm

Add dados do Índice Firjan de Gestão Fiscal

2023-12-01 11:13 UTC, folhesgabriel requested changes

2023-12-01 11:18 UTC, lucasnascm commented on models/br_firjan_ifgf/code/[dados]_br_firjan_ifgf.ipynb
> +{
É o código de tratamento da base :)

2023-12-01 12:04 UTC, folhesgabriel approved these changes

2024-01-22 12:58 UTC, tricktx approved these changes

2024-01-22 13:33 UTC, merged