add: br_ibge_pam models + code
basedosdados/queries-basedosdados pull request #539
Opened 2024-04-10 15:22 UTC by jeantozzi

2024-04-10 17:37 UTC, folhesgabriel requested changes

2024-04-10 17:37 UTC, folhesgabriel commented on models/br_ibge_pam/br_ibge_pam__lavoura_permanente.sql
> +select
Cara vale particionar e clusterizar essa tabela! Conferi lavoura permanente e tem ~10M linhas. Acho válido pelo menos particionar por ano e talvez clusterizar por mes sigla_uf pode.

2024-04-10 17:37 UTC, folhesgabriel commented on models/br_ibge_pam/br_ibge_pam__lavoura_temporaria.sql
> +select
mesmo vale p/ lavoura temporaria

2024-04-10 17:37 UTC, folhesgabriel commented on models/br_ibge_pam/code/api_to_json.py
> +async def main(years, variables, categories):
Adicionar Type Hint e documentação das funções

2024-04-12 03:14 UTC, jeantozzi commented on models/br_ibge_pam/code/api_to_json.py
> +async def main(years, variables, categories):
Feito!

2024-04-12 03:14 UTC, jeantozzi commented on models/br_ibge_pam/br_ibge_pam__lavoura_temporaria.sql
> +select
Feito!

2024-04-12 03:14 UTC, jeantozzi commented on models/br_ibge_pam/br_ibge_pam__lavoura_permanente.sql
> +select
Feito!

2024-04-12 15:09 UTC, folhesgabriel approved these changes

2024-04-12 15:10 UTC, merged