[dbt] add custom tests
basedosdados/queries-basedosdados pull request #570
Opened 2024-05-02 18:09 UTC by folhesgabriel

closes #545 

**1. Adiciona novos testes customizados**
- `custom_relationships`: permite settar valores que podem ser ignorados manualmente ou informar uma proporção de erros tolerável.
- `custom_unique_combinations_of_columns`: permite  settar uma proporção de erros tolerável.

**2. Adiciona documentação dos testes customizados na Wiki**
- ver [link](https://github.com/basedosdados/pipelines/wiki/Testar-modelos-dbt-localmente#testes-customizados)

**3. Adiciona documentação do config where na wiki**

**4. Adiciona explicação do uso  da macro custom_get_where_subquery  com config where na wiki para fazer testes incrementais**
- ver [link](https://github.com/basedosdados/pipelines/wiki/Testar-modelos-dbt-localmente#uso-do-where-com-a-macro-customizada-custom_get_where_subquery-localizada-em-modelsmacros)

2024-05-02 18:22 UTC, arthurfg approved these changes
mt bom

2024-05-02 18:36 UTC, tricktx commented
Muuuito bom! Parabéns, Pisa.

2024-05-02 19:14 UTC, laura-l-amaral requested changes
Ficou excelente! Apenas 2 pontos de melhoria importantes aqui:
- [x] deixar a proporção como um número entre 0 e 1 (tipo 0.05 ao inves de 5 para representar 5%) só pra manter o padrão com os outros testes que o dbt já oferece
- [ ] incluir opção de formato de data no teste incremental (não limitar apenas quando tiver as colunas de ano e mes), é importante incluir essa macro em tabelas como cnpj que só tem uma data

2024-05-03 17:16 UTC, laura-l-amaral approved these changes

2024-05-06 15:10 UTC, merged