[dbt]: Add `br_bd_diretorios_brasil.setor_censitario_{2010, 2022}`
basedosdados/queries-basedosdados pull request #606
Opened 2024-05-16 18:16 UTC by aspeddro

2024-05-22 19:02 UTC, folhesgabriel approved these changes

2024-06-11 13:16 UTC, laura-l-amaral approved these changes

2024-06-13 19:16 UTC, laura-l-amaral requested changes
Tem mais de um setor censitário por id
![image](https://github.com/basedosdados/queries-basedosdados/assets/100051996/bc52aff4-0bfd-4309-9191-068bde09811e)

2024-06-14 20:14 UTC, aspeddro commented on models/br_bd_diretorios_brasil/br_bd_diretorios_brasil__setor_censitario_2022.sql
> +    ) as d
Removi os duplicados. O problema era que a tabela `distrito` que tem a coluna ano. Provavelmente o `id_distrito` pode mudar dependendo do ano. O mais recente é 2010. Não sei se é o ideal, o que você acha @laura-l-amaral ?

2024-07-09 20:49 UTC, laura-l-amaral commented
no #668 o @tricktx puxou as queries que o pedro fez aqui e resolveu outros problemas de diretórios

2024-07-09 20:49 UTC, laura-l-amaral commented
> no #668 o @tricktx puxou as queries que o pedro fez aqui e resolveu outros problemas de diretórios

2024-07-09 20:49 UTC, closed without merging