[feat] table approve in dicionario rais
basedosdados/queries-basedosdados pull request #625
Opened 2024-05-28 13:42 UTC by tricktx

2024-06-13 16:41 UTC, laura-l-amaral approved these changes

2024-06-13 18:20 UTC, laura-l-amaral approved these changes

2024-06-13 20:45 UTC, laura-l-amaral requested changes
Parece que aconteceu algo errado aqui, principalmente na parte de bairros, na versão de prod não tem o mesmo código de bairro para bairros com nomes diferentes

**Dev**
![image](https://github.com/basedosdados/queries-basedosdados/assets/100051996/c263cf6d-5e87-4577-8ec4-611536bec814)  
  
**Prod**
![image](https://github.com/basedosdados/queries-basedosdados/assets/100051996/93937753-d848-48fd-b3a0-b1143d00110c)

2024-06-14 03:18 UTC, tricktx commented
Realmente há algo estranho, estou verificando, @laura-l-amaral.

2024-06-14 12:08 UTC, tricktx commented
As chaves não estão erradas, o que há de errado é a cobertura temporal. 
No dicionário, há um arquivo (1996(1)2000) que realmente diverge dos demais anos em relação aos bairros. 
Segue o exemplo: 

1996(1)2000: 
![image](https://github.com/basedosdados/queries-basedosdados/assets/105399231/1e4b6f55-0e46-4098-9a24-6ca5a08ff547)

Demais anos:
![image](https://github.com/basedosdados/queries-basedosdados/assets/105399231/b64857a8-4cfd-4fb6-b3b3-7c17d2b3089f)

2024-06-14 12:50 UTC, laura-l-amaral commented
nesses prints que vc mandou não tem nenhuma chave que se sobrepoe trick, vc consegue puxar um exemplo que se sobrepoe?

2024-06-14 12:51 UTC, laura-l-amaral commented
na tabela de vinculos isso não acontece?

2024-06-14 13:12 UTC, laura-l-amaral commented
Olhando aqui nas planilhas de dicionario não encontrei esse arquivo que vc chamou de 1996(1)2000, me passa o caminho certinho?

2024-06-14 13:17 UTC, tricktx commented
Eu digitei errado, perdão. Na verdade, o arquivo é `10RAIS_estabelecimento_layout1999e2000`, eu fui digitar para a nossa versão e acabei me enrolando. Perdão. 

Peço que abra o arquivo citado acima, por gentileza. Ela consta no [drive](https://drive.google.com/drive/u/0/folders/17DLSIKaxWhOyPdY8zefKZb1graqNxnsK)

2024-06-14 16:20 UTC, laura-l-amaral commented
Apenas o ano de 1999 e 2000 tem códigos diferentes e apenas na tabela de estabelecimentos, a tabela de vinculos tem um único padrão para todos os anos.

O melhor seria a gente fazer a conversão entre os dicionarios para padronizar entre anos. Fiz um procv e parece que seria tranquilo fazer o depara. Depois que o dahis arrumar os problemas que temos hoje mapeados (resubir os dados de 2019 e 2022) podemos aplicar esse depara via dbt.

Por hora vamos só arrumar a cobertura temporal do dicionario

2024-06-14 19:21 UTC, jeantozzi approved these changes

2024-06-14 19:54 UTC, merged