[feat-br_inep_censo_educacao_superior] Add test in inep educacao superior
basedosdados/queries-basedosdados pull request #632
Opened 2024-06-05 14:16 UTC by tricktx

2024-06-05 14:33 UTC, laura-l-amaral commented on dbt_project.yml
> +       - REVOKE `roles/bigquery.dataViewer` ON TABLE {{ this }} FROM "specialGroup:allUsers"
aproveitando aqui, acho que pode deletar esse post-hook desse conjunto

2024-06-05 20:26 UTC, laura-l-amaral commented on models/br_me_rais/br_me_rais__dicionario.sql
> +    safe_cast(replace(cobertura_temporal, '-1', '(1)') as string) cobertura_temporal,
esse arquivo não era pra estar só no pr da rais mesmo?

2024-06-05 20:35 UTC, tricktx commented on models/br_me_rais/br_me_rais__dicionario.sql
> +    safe_cast(replace(cobertura_temporal, '-1', '(1)') as string) cobertura_temporal,
Prontinho. Tinha subido essa mudança e eu não observei.

2024-06-05 20:56 UTC, laura-l-amaral approved these changes

2024-06-05 21:01 UTC, laura-l-amaral requested changes
ta faltando o schema da tabela de ies

2024-06-06 19:12 UTC, laura-l-amaral approved these changes

2024-06-07 18:59 UTC, merged