[dbt]:br_simet_educacao_conectada
basedosdados/queries-basedosdados pull request #836
Opened 2024-11-26 19:37 UTC by carmemneri

add model dbt in prod

2024-11-26 20:51 UTC, aspeddro approved these changes
Tudo certo Carmem!! 🎉

2024-11-26 20:51 UTC, aspeddro commented on dbt_project.yml
Copilot:

The file has changes for all lines because it appears to have undergone a change in line endings. Different operating systems sometimes use different characters to represent the end of a line (e.g., `CRLF` for Windows, `LF` for Unix/Linux). When a file is converted from one line ending format to another, Git detects changes on all lines, even though the actual content might not have changed. 

The specific selection you've highlighted adds a new section for `br_simet_educacao_conectada` with the following properties:
- `+materialized: table`: Specifies that the object is materialized as a table.
- `+schema: br_simet_educacao_conectada`: Specifies the schema for the object.

This means that a new table with the schema `br_simet_educacao_conectada` is being added to the `dbt_project.yml` configuration.

2024-11-26 20:51 UTC, aspeddro commented on dbt_project.yml
Na main tá com encoding `dos`. `unix` deve ser o padrão

2024-11-27 12:00 UTC, laura-l-amaral requested changes

2024-11-27 12:00 UTC, laura-l-amaral commented on models/br_simet_educacao_conectada/escola.sql
> +    config(
O nome do arquivo .sql deve ser `br_simet_educacao_conectada__escola`

2024-12-13 13:40 UTC, laura-l-amaral approved these changes

2025-02-04 14:53 UTC, merged